/* A Bison parser, made by GNU Bison 3.8.2.  */

/* Bison implementation for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2021 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* C LALR(1) parser skeleton written by Richard Stallman, by
   simplifying the original so-called "semantic" parser.  */

/* DO NOT RELY ON FEATURES THAT ARE NOT DOCUMENTED in the manual,
   especially those whose name start with YY_ or yy_.  They are
   private implementation details that can be changed or removed.  */

/* All symbols defined below should begin with yy or YY, to avoid
   infringing on user name space.  This should be done even for local
   variables, as they might otherwise be expanded by user macros.
   There are some unavoidable exceptions within include files to
   define necessary library symbols; they are noted "INFRINGES ON
   USER NAME SPACE" below.  */

/* Identify Bison output, and Bison version.  */
#define YYBISON 30802

/* Bison version string.  */
#define YYBISON_VERSION "3.8.2"

/* Skeleton name.  */
#define YYSKELETON_NAME "yacc.c"

/* Pure parsers.  */
#define YYPURE 0

/* Push parsers.  */
#define YYPUSH 0

/* Pull parsers.  */
#define YYPULL 1




/* First part of user prologue.  */
#line 1 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"

#include <cstdio>
#include <cstring>

// 词法分析头文件
#include "FlexLexer.h"

// bison生成的头文件
#include "BisonParser.h"

// 抽象语法树函数定义原型头文件
#include "AST.h"

#include "IntegerType.h"

// LR分析失败时所调用函数的原型声明
void yyerror(char * msg);


#line 91 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"

# ifndef YY_CAST
#  ifdef __cplusplus
#   define YY_CAST(Type, Val) static_cast<Type> (Val)
#   define YY_REINTERPRET_CAST(Type, Val) reinterpret_cast<Type> (Val)
#  else
#   define YY_CAST(Type, Val) ((Type) (Val))
#   define YY_REINTERPRET_CAST(Type, Val) ((Type) (Val))
#  endif
# endif
# ifndef YY_NULLPTR
#  if defined __cplusplus
#   if 201103L <= __cplusplus
#    define YY_NULLPTR nullptr
#   else
#    define YY_NULLPTR 0
#   endif
#  else
#   define YY_NULLPTR ((void*)0)
#  endif
# endif

#include "MiniCBison.h"
/* Symbol kind.  */
enum yysymbol_kind_t
{
  YYSYMBOL_YYEMPTY = -2,
  YYSYMBOL_YYEOF = 0,                      /* "end of file"  */
  YYSYMBOL_YYerror = 1,                    /* error  */
  YYSYMBOL_YYUNDEF = 2,                    /* "invalid token"  */
  YYSYMBOL_T_DIGIT = 3,                    /* T_DIGIT  */
  YYSYMBOL_T_FLOAT_DIGIT = 4,              /* T_FLOAT_DIGIT  */
  YYSYMBOL_T_ID = 5,                       /* T_ID  */
  YYSYMBOL_T_INT = 6,                      /* T_INT  */
  YYSYMBOL_T_FLOAT = 7,                    /* T_FLOAT  */
  YYSYMBOL_T_RETURN = 8,                   /* T_RETURN  */
  YYSYMBOL_T_VOID = 9,                     /* T_VOID  */
  YYSYMBOL_T_CONST = 10,                   /* T_CONST  */
  YYSYMBOL_T_SEMICOLON = 11,               /* T_SEMICOLON  */
  YYSYMBOL_T_L_PAREN = 12,                 /* T_L_PAREN  */
  YYSYMBOL_T_R_PAREN = 13,                 /* T_R_PAREN  */
  YYSYMBOL_T_L_BRACE = 14,                 /* T_L_BRACE  */
  YYSYMBOL_T_R_BRACE = 15,                 /* T_R_BRACE  */
  YYSYMBOL_T_COMMA = 16,                   /* T_COMMA  */
  YYSYMBOL_T_L_BRACKET = 17,               /* T_L_BRACKET  */
  YYSYMBOL_T_R_BRACKET = 18,               /* T_R_BRACKET  */
  YYSYMBOL_T_ASSIGN = 19,                  /* T_ASSIGN  */
  YYSYMBOL_T_SUB = 20,                     /* T_SUB  */
  YYSYMBOL_T_ADD = 21,                     /* T_ADD  */
  YYSYMBOL_T_MUL = 22,                     /* T_MUL  */
  YYSYMBOL_T_DIV = 23,                     /* T_DIV  */
  YYSYMBOL_T_MOD = 24,                     /* T_MOD  */
  YYSYMBOL_T_LT = 25,                      /* T_LT  */
  YYSYMBOL_T_LE = 26,                      /* T_LE  */
  YYSYMBOL_T_GT = 27,                      /* T_GT  */
  YYSYMBOL_T_GE = 28,                      /* T_GE  */
  YYSYMBOL_T_EQ = 29,                      /* T_EQ  */
  YYSYMBOL_T_NE = 30,                      /* T_NE  */
  YYSYMBOL_T_LOGICAL_AND = 31,             /* T_LOGICAL_AND  */
  YYSYMBOL_T_LOGICAL_OR = 32,              /* T_LOGICAL_OR  */
  YYSYMBOL_T_LOGICAL_NOT = 33,             /* T_LOGICAL_NOT  */
  YYSYMBOL_T_IF = 34,                      /* T_IF  */
  YYSYMBOL_T_ELSE = 35,                    /* T_ELSE  */
  YYSYMBOL_T_WHILE = 36,                   /* T_WHILE  */
  YYSYMBOL_T_BREAK = 37,                   /* T_BREAK  */
  YYSYMBOL_T_CONTINUE = 38,                /* T_CONTINUE  */
  YYSYMBOL_UMINUS = 39,                    /* UMINUS  */
  YYSYMBOL_YYACCEPT = 40,                  /* $accept  */
  YYSYMBOL_CompileUnit = 41,               /* CompileUnit  */
  YYSYMBOL_FuncDef = 42,                   /* FuncDef  */
  YYSYMBOL_FormalParams = 43,              /* FormalParams  */
  YYSYMBOL_FormalParam = 44,               /* FormalParam  */
  YYSYMBOL_Block = 45,                     /* Block  */
  YYSYMBOL_BlockItemList = 46,             /* BlockItemList  */
  YYSYMBOL_BlockItem = 47,                 /* BlockItem  */
  YYSYMBOL_VarDecl = 48,                   /* VarDecl  */
  YYSYMBOL_VarDeclExpr = 49,               /* VarDeclExpr  */
  YYSYMBOL_ArrayDims = 50,                 /* ArrayDims  */
  YYSYMBOL_ArrayIndices = 51,              /* ArrayIndices  */
  YYSYMBOL_VarDef = 52,                    /* VarDef  */
  YYSYMBOL_ArrayInitList = 53,             /* ArrayInitList  */
  YYSYMBOL_BasicType = 54,                 /* BasicType  */
  YYSYMBOL_Statement = 55,                 /* Statement  */
  YYSYMBOL_Expr = 56,                      /* Expr  */
  YYSYMBOL_LogicalOrExp = 57,              /* LogicalOrExp  */
  YYSYMBOL_LogicalAndExp = 58,             /* LogicalAndExp  */
  YYSYMBOL_RelExp = 59,                    /* RelExp  */
  YYSYMBOL_AddExp = 60,                    /* AddExp  */
  YYSYMBOL_MulExp = 61,                    /* MulExp  */
  YYSYMBOL_UnaryExp = 62,                  /* UnaryExp  */
  YYSYMBOL_PrimaryExp = 63,                /* PrimaryExp  */
  YYSYMBOL_RealParamList = 64,             /* RealParamList  */
  YYSYMBOL_LVal = 65                       /* LVal  */
};
typedef enum yysymbol_kind_t yysymbol_kind_t;




#ifdef short
# undef short
#endif

/* On compilers that do not define __PTRDIFF_MAX__ etc., make sure
   <limits.h> and (if available) <stdint.h> are included
   so that the code can choose integer types of a good width.  */

#ifndef __PTRDIFF_MAX__
# include <limits.h> /* INFRINGES ON USER NAME SPACE */
# if defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stdint.h> /* INFRINGES ON USER NAME SPACE */
#  define YY_STDINT_H
# endif
#endif

/* Narrow types that promote to a signed type and that can represent a
   signed or unsigned integer of at least N bits.  In tables they can
   save space and decrease cache pressure.  Promoting to a signed type
   helps avoid bugs in integer arithmetic.  */

#ifdef __INT_LEAST8_MAX__
typedef __INT_LEAST8_TYPE__ yytype_int8;
#elif defined YY_STDINT_H
typedef int_least8_t yytype_int8;
#else
typedef signed char yytype_int8;
#endif

#ifdef __INT_LEAST16_MAX__
typedef __INT_LEAST16_TYPE__ yytype_int16;
#elif defined YY_STDINT_H
typedef int_least16_t yytype_int16;
#else
typedef short yytype_int16;
#endif

/* Work around bug in HP-UX 11.23, which defines these macros
   incorrectly for preprocessor constants.  This workaround can likely
   be removed in 2023, as HPE has promised support for HP-UX 11.23
   (aka HP-UX 11i v2) only through the end of 2022; see Table 2 of
   <https://h20195.www2.hpe.com/V2/getpdf.aspx/4AA4-7673ENW.pdf>.  */
#ifdef __hpux
# undef UINT_LEAST8_MAX
# undef UINT_LEAST16_MAX
# define UINT_LEAST8_MAX 255
# define UINT_LEAST16_MAX 65535
#endif

#if defined __UINT_LEAST8_MAX__ && __UINT_LEAST8_MAX__ <= __INT_MAX__
typedef __UINT_LEAST8_TYPE__ yytype_uint8;
#elif (!defined __UINT_LEAST8_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST8_MAX <= INT_MAX)
typedef uint_least8_t yytype_uint8;
#elif !defined __UINT_LEAST8_MAX__ && UCHAR_MAX <= INT_MAX
typedef unsigned char yytype_uint8;
#else
typedef short yytype_uint8;
#endif

#if defined __UINT_LEAST16_MAX__ && __UINT_LEAST16_MAX__ <= __INT_MAX__
typedef __UINT_LEAST16_TYPE__ yytype_uint16;
#elif (!defined __UINT_LEAST16_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST16_MAX <= INT_MAX)
typedef uint_least16_t yytype_uint16;
#elif !defined __UINT_LEAST16_MAX__ && USHRT_MAX <= INT_MAX
typedef unsigned short yytype_uint16;
#else
typedef int yytype_uint16;
#endif

#ifndef YYPTRDIFF_T
# if defined __PTRDIFF_TYPE__ && defined __PTRDIFF_MAX__
#  define YYPTRDIFF_T __PTRDIFF_TYPE__
#  define YYPTRDIFF_MAXIMUM __PTRDIFF_MAX__
# elif defined PTRDIFF_MAX
#  ifndef ptrdiff_t
#   include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  endif
#  define YYPTRDIFF_T ptrdiff_t
#  define YYPTRDIFF_MAXIMUM PTRDIFF_MAX
# else
#  define YYPTRDIFF_T long
#  define YYPTRDIFF_MAXIMUM LONG_MAX
# endif
#endif

#ifndef YYSIZE_T
# ifdef __SIZE_TYPE__
#  define YYSIZE_T __SIZE_TYPE__
# elif defined size_t
#  define YYSIZE_T size_t
# elif defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  define YYSIZE_T size_t
# else
#  define YYSIZE_T unsigned
# endif
#endif

#define YYSIZE_MAXIMUM                                  \
  YY_CAST (YYPTRDIFF_T,                                 \
           (YYPTRDIFF_MAXIMUM < YY_CAST (YYSIZE_T, -1)  \
            ? YYPTRDIFF_MAXIMUM                         \
            : YY_CAST (YYSIZE_T, -1)))

#define YYSIZEOF(X) YY_CAST (YYPTRDIFF_T, sizeof (X))


/* Stored state numbers (used for stacks). */
typedef yytype_uint8 yy_state_t;

/* State numbers in computations.  */
typedef int yy_state_fast_t;

#ifndef YY_
# if defined YYENABLE_NLS && YYENABLE_NLS
#  if ENABLE_NLS
#   include <libintl.h> /* INFRINGES ON USER NAME SPACE */
#   define YY_(Msgid) dgettext ("bison-runtime", Msgid)
#  endif
# endif
# ifndef YY_
#  define YY_(Msgid) Msgid
# endif
#endif


#ifndef YY_ATTRIBUTE_PURE
# if defined __GNUC__ && 2 < __GNUC__ + (96 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_PURE __attribute__ ((__pure__))
# else
#  define YY_ATTRIBUTE_PURE
# endif
#endif

#ifndef YY_ATTRIBUTE_UNUSED
# if defined __GNUC__ && 2 < __GNUC__ + (7 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_UNUSED __attribute__ ((__unused__))
# else
#  define YY_ATTRIBUTE_UNUSED
# endif
#endif

/* Suppress unused-variable warnings by "using" E.  */
#if ! defined lint || defined __GNUC__
# define YY_USE(E) ((void) (E))
#else
# define YY_USE(E) /* empty */
#endif

/* Suppress an incorrect diagnostic about yylval being uninitialized.  */
#if defined __GNUC__ && ! defined __ICC && 406 <= __GNUC__ * 100 + __GNUC_MINOR__
# if __GNUC__ * 100 + __GNUC_MINOR__ < 407
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")
# else
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")              \
    _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
# endif
# define YY_IGNORE_MAYBE_UNINITIALIZED_END      \
    _Pragma ("GCC diagnostic pop")
#else
# define YY_INITIAL_VALUE(Value) Value
#endif
#ifndef YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_END
#endif
#ifndef YY_INITIAL_VALUE
# define YY_INITIAL_VALUE(Value) /* Nothing. */
#endif

#if defined __cplusplus && defined __GNUC__ && ! defined __ICC && 6 <= __GNUC__
# define YY_IGNORE_USELESS_CAST_BEGIN                          \
    _Pragma ("GCC diagnostic push")                            \
    _Pragma ("GCC diagnostic ignored \"-Wuseless-cast\"")
# define YY_IGNORE_USELESS_CAST_END            \
    _Pragma ("GCC diagnostic pop")
#endif
#ifndef YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_END
#endif


#define YY_ASSERT(E) ((void) (0 && (E)))

#if !defined yyoverflow

/* The parser invokes alloca or malloc; define the necessary symbols.  */

# ifdef YYSTACK_USE_ALLOCA
#  if YYSTACK_USE_ALLOCA
#   ifdef __GNUC__
#    define YYSTACK_ALLOC __builtin_alloca
#   elif defined __BUILTIN_VA_ARG_INCR
#    include <alloca.h> /* INFRINGES ON USER NAME SPACE */
#   elif defined _AIX
#    define YYSTACK_ALLOC __alloca
#   elif defined _MSC_VER
#    include <malloc.h> /* INFRINGES ON USER NAME SPACE */
#    define alloca _alloca
#   else
#    define YYSTACK_ALLOC alloca
#    if ! defined _ALLOCA_H && ! defined EXIT_SUCCESS
#     include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
      /* Use EXIT_SUCCESS as a witness for stdlib.h.  */
#     ifndef EXIT_SUCCESS
#      define EXIT_SUCCESS 0
#     endif
#    endif
#   endif
#  endif
# endif

# ifdef YYSTACK_ALLOC
   /* Pacify GCC's 'empty if-body' warning.  */
#  define YYSTACK_FREE(Ptr) do { /* empty */; } while (0)
#  ifndef YYSTACK_ALLOC_MAXIMUM
    /* The OS might guarantee only one guard page at the bottom of the stack,
       and a page size can be as small as 4096 bytes.  So we cannot safely
       invoke alloca (N) if N exceeds 4096.  Use a slightly smaller number
       to allow for a few compiler-allocated temporary stack slots.  */
#   define YYSTACK_ALLOC_MAXIMUM 4032 /* reasonable circa 2006 */
#  endif
# else
#  define YYSTACK_ALLOC YYMALLOC
#  define YYSTACK_FREE YYFREE
#  ifndef YYSTACK_ALLOC_MAXIMUM
#   define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#  endif
#  if (defined __cplusplus && ! defined EXIT_SUCCESS \
       && ! ((defined YYMALLOC || defined malloc) \
             && (defined YYFREE || defined free)))
#   include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#   ifndef EXIT_SUCCESS
#    define EXIT_SUCCESS 0
#   endif
#  endif
#  ifndef YYMALLOC
#   define YYMALLOC malloc
#   if ! defined malloc && ! defined EXIT_SUCCESS
void *malloc (YYSIZE_T); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
#  ifndef YYFREE
#   define YYFREE free
#   if ! defined free && ! defined EXIT_SUCCESS
void free (void *); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
# endif
#endif /* !defined yyoverflow */

#if (! defined yyoverflow \
     && (! defined __cplusplus \
         || (defined YYSTYPE_IS_TRIVIAL && YYSTYPE_IS_TRIVIAL)))

/* A type that is properly aligned for any stack member.  */
union yyalloc
{
  yy_state_t yyss_alloc;
  YYSTYPE yyvs_alloc;
};

/* The size of the maximum gap between one aligned stack and the next.  */
# define YYSTACK_GAP_MAXIMUM (YYSIZEOF (union yyalloc) - 1)

/* The size of an array large to enough to hold all stacks, each with
   N elements.  */
# define YYSTACK_BYTES(N) \
     ((N) * (YYSIZEOF (yy_state_t) + YYSIZEOF (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)

# define YYCOPY_NEEDED 1

/* Relocate STACK from its old location to the new one.  The
   local variables YYSIZE and YYSTACKSIZE give the old and new number of
   elements in the stack, and YYPTR gives the new location of the
   stack.  Advance YYPTR to a properly aligned location for the next
   stack.  */
# define YYSTACK_RELOCATE(Stack_alloc, Stack)                           \
    do                                                                  \
      {                                                                 \
        YYPTRDIFF_T yynewbytes;                                         \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * YYSIZEOF (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / YYSIZEOF (*yyptr);                        \
      }                                                                 \
    while (0)

#endif

#if defined YYCOPY_NEEDED && YYCOPY_NEEDED
/* Copy COUNT objects from SRC to DST.  The source and destination do
   not overlap.  */
# ifndef YYCOPY
#  if defined __GNUC__ && 1 < __GNUC__
#   define YYCOPY(Dst, Src, Count) \
      __builtin_memcpy (Dst, Src, YY_CAST (YYSIZE_T, (Count)) * sizeof (*(Src)))
#  else
#   define YYCOPY(Dst, Src, Count)              \
      do                                        \
        {                                       \
          YYPTRDIFF_T yyi;                      \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (Dst)[yyi] = (Src)[yyi];            \
        }                                       \
      while (0)
#  endif
# endif
#endif /* !YYCOPY_NEEDED */

/* YYFINAL -- State number of the termination state.  */
#define YYFINAL  12
/* YYLAST -- Last index in YYTABLE.  */
#define YYLAST   272

/* YYNTOKENS -- Number of terminals.  */
#define YYNTOKENS  40
/* YYNNTS -- Number of nonterminals.  */
#define YYNNTS  26
/* YYNRULES -- Number of rules.  */
#define YYNRULES  86
/* YYNSTATES -- Number of states.  */
#define YYNSTATES  165

/* YYMAXUTOK -- Last valid token kind.  */
#define YYMAXUTOK   294


/* YYTRANSLATE(TOKEN-NUM) -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex, with out-of-bounds checking.  */
#define YYTRANSLATE(YYX)                                \
  (0 <= (YYX) && (YYX) <= YYMAXUTOK                     \
   ? YY_CAST (yysymbol_kind_t, yytranslate[YYX])        \
   : YYSYMBOL_YYUNDEF)

/* YYTRANSLATE[TOKEN-NUM] -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex.  */
static const yytype_int8 yytranslate[] =
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
       5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
      15,    16,    17,    18,    19,    20,    21,    22,    23,    24,
      25,    26,    27,    28,    29,    30,    31,    32,    33,    34,
      35,    36,    37,    38,    39
};

#if YYDEBUG
/* YYRLINE[YYN] -- Source line where rule number YYN was defined.  */
static const yytype_int16 yyrline[] =
{
       0,   103,   103,   111,   117,   122,   129,   147,   163,   181,
     202,   206,   213,   217,   229,   251,   283,   289,   300,   305,
     314,   318,   329,   335,   372,   409,   450,   454,   461,   465,
     472,   484,   496,   508,   528,   548,   563,   569,   576,   588,
     593,   607,   610,   619,   625,   631,   637,   643,   649,   655,
     659,   663,   667,   671,   678,   684,   687,   693,   696,   702,
     705,   708,   711,   714,   717,   720,   726,   729,   732,   748,
     751,   754,   757,   767,   773,   789,   804,   809,   813,   822,
     826,   832,   838,   848,   852,   859,   868
};
#endif

/** Accessing symbol of state STATE.  */
#define YY_ACCESSING_SYMBOL(State) YY_CAST (yysymbol_kind_t, yystos[State])

#if YYDEBUG || 0
/* The user-facing name of the symbol whose (internal) number is
   YYSYMBOL.  No bounds checking.  */
static const char *yysymbol_name (yysymbol_kind_t yysymbol) YY_ATTRIBUTE_UNUSED;

/* YYTNAME[SYMBOL-NUM] -- String name of the symbol SYMBOL-NUM.
   First, the terminals, then, starting at YYNTOKENS, nonterminals.  */
static const char *const yytname[] =
{
  "\"end of file\"", "error", "\"invalid token\"", "T_DIGIT",
  "T_FLOAT_DIGIT", "T_ID", "T_INT", "T_FLOAT", "T_RETURN", "T_VOID",
  "T_CONST", "T_SEMICOLON", "T_L_PAREN", "T_R_PAREN", "T_L_BRACE",
  "T_R_BRACE", "T_COMMA", "T_L_BRACKET", "T_R_BRACKET", "T_ASSIGN",
  "T_SUB", "T_ADD", "T_MUL", "T_DIV", "T_MOD", "T_LT", "T_LE", "T_GT",
  "T_GE", "T_EQ", "T_NE", "T_LOGICAL_AND", "T_LOGICAL_OR", "T_LOGICAL_NOT",
  "T_IF", "T_ELSE", "T_WHILE", "T_BREAK", "T_CONTINUE", "UMINUS",
  "$accept", "CompileUnit", "FuncDef", "FormalParams", "FormalParam",
  "Block", "BlockItemList", "BlockItem", "VarDecl", "VarDeclExpr",
  "ArrayDims", "ArrayIndices", "VarDef", "ArrayInitList", "BasicType",
  "Statement", "Expr", "LogicalOrExp", "LogicalAndExp", "RelExp", "AddExp",
  "MulExp", "UnaryExp", "PrimaryExp", "RealParamList", "LVal", YY_NULLPTR
};

static const char *
yysymbol_name (yysymbol_kind_t yysymbol)
{
  return yytname[yysymbol];
}
#endif

#define YYPACT_NINF (-137)

#define yypact_value_is_default(Yyn) \
  ((Yyn) == YYPACT_NINF)

#define YYTABLE_NINF (-1)

#define yytable_value_is_error(Yyn) \
  0

/* YYPACT[STATE-NUM] -- Index in YYTABLE of the portion describing
   STATE-NUM.  */
static const yytype_int16 yypact[] =
{
     142,  -137,  -137,     0,   111,    46,  -137,  -137,    13,    10,
      19,    42,  -137,  -137,  -137,  -137,    42,    -1,  -137,    93,
      24,  -137,  -137,   106,   239,   239,    84,    45,    12,  -137,
      61,    45,    21,  -137,  -137,   104,   239,   239,   239,   239,
      52,    55,    43,   117,   116,    62,  -137,  -137,  -137,  -137,
     239,    88,    57,  -137,    45,   111,   105,  -137,    45,    76,
     239,   122,    97,  -137,  -137,  -137,  -137,   239,   239,   239,
     239,   239,   239,   239,   239,   239,   239,   239,   239,   239,
     151,    18,   202,  -137,  -137,   159,   172,   174,   180,  -137,
     120,  -137,  -137,    42,  -137,   185,   189,  -137,  -137,   216,
     182,  -137,  -137,  -137,    60,   192,   239,  -137,    43,   117,
     116,   116,   116,   116,   116,   116,    62,    62,  -137,  -137,
    -137,  -137,   183,  -137,   147,  -137,  -137,   204,   239,   239,
    -137,  -137,  -137,  -137,  -137,   239,   207,  -137,   239,  -137,
     208,  -137,   150,  -137,   236,  -137,   212,   214,   218,   182,
    -137,  -137,  -137,   197,  -137,   156,   156,  -137,  -137,   157,
     196,  -137,  -137,   156,  -137
};

/* YYDEFACT[STATE-NUM] -- Default reduction number in state STATE-NUM.
   Performed when YYTABLE does not specify something else to do.  Zero
   means the default is an error.  */
static const yytype_int8 yydefact[] =
{
       0,    41,    42,     0,     0,     0,     2,     3,     0,     0,
       0,     0,     1,     4,     5,    22,     0,    30,    23,     0,
      30,    24,    25,     0,     0,     0,    31,     0,     0,    10,
       0,     0,     0,    80,    82,    85,     0,     0,     0,     0,
       0,    54,    55,    57,    59,    66,    69,    73,    81,    32,
       0,     0,     0,     8,     0,     0,    12,     6,     0,     0,
       0,    86,     0,    76,    77,    78,    26,     0,     0,     0,
       0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       0,     0,     0,    48,    16,     0,     0,     0,     0,    46,
       0,    18,    21,     0,    20,     0,    81,     9,    11,     0,
      13,     7,    74,    83,     0,     0,     0,    79,    56,    58,
      60,    61,    62,    63,    64,    65,    68,    67,    70,    71,
      72,    27,     0,    33,     0,    35,    44,     0,     0,     0,
      52,    53,    17,    19,    47,     0,    14,    75,     0,    28,
       0,    38,     0,    34,     0,    43,     0,     0,     0,    15,
      84,    29,    37,     0,    36,     0,     0,    45,    40,     0,
      49,    51,    39,     0,    50
};

/* YYPGOTO[NTERM-NUM].  */
static const yytype_int16 yypgoto[] =
{
    -137,  -137,   227,   210,   190,   -14,  -137,   148,   133,  -137,
     -53,  -137,   139,  -108,     2,  -136,   -24,  -137,   179,   184,
     109,    99,   -29,  -137,  -137,   -48
};

/* YYDEFGOTO[NTERM-NUM].  */
static const yytype_int8 yydefgoto[] =
{
       0,     5,     6,    28,    29,    89,    90,    91,    92,     8,
      26,    61,    18,   124,    30,    94,    95,    41,    42,    43,
      44,    45,    46,    47,   104,    48
};

/* YYTABLE[YYPACT[STATE-NUM]] -- What to do in state STATE-NUM.  If
   positive, shift that token.  If negative, reduce the rule whose
   number is the opposite.  If YYTABLE_NINF, syntax error.  */
static const yytype_uint8 yytable[] =
{
      40,    49,     9,   100,    96,    10,    11,     9,    63,    64,
      65,    23,    62,    53,   142,    17,    24,    57,    25,   160,
     161,    33,    34,    35,    15,    54,    80,   164,    55,    16,
      36,    19,   122,   123,    58,   103,   105,    55,    37,    38,
      97,    24,    96,    25,   101,   159,    12,    20,   118,   119,
     120,    39,     1,     2,    93,     3,     4,   125,   127,    52,
      33,    34,    35,     1,     2,    82,    56,     4,    83,    36,
      66,    52,    84,   137,    68,    40,   138,    37,    38,    33,
      34,    35,   140,   149,    77,    78,    79,    67,    36,   102,
      39,    85,    93,    86,    87,    88,    37,    38,   125,     1,
       2,    50,    81,    51,   146,   147,    27,    96,    96,    39,
     107,   148,     1,     2,   150,    96,    59,     1,     2,    31,
     154,    60,    99,    33,    34,    35,     1,     2,    82,   125,
       4,    83,    36,     7,    52,   132,    75,    76,    14,   106,
      37,    38,    69,    70,    71,    72,    73,    74,     1,     2,
      21,     3,     4,    39,    85,    22,    86,    87,    88,    33,
      34,    35,   143,   144,    82,   152,   144,    83,    36,   121,
      52,   128,   162,   144,   116,   117,    37,    38,   110,   111,
     112,   113,   114,   115,   129,   130,    33,    34,    35,    39,
      85,   131,    86,    87,    88,    36,   134,   122,   141,    50,
      33,    34,    35,    37,    38,    33,    34,    35,   135,    36,
     139,   122,   158,   126,    36,   145,    39,    37,    38,    33,
      34,    35,    37,    38,    24,   155,   151,   156,    36,   157,
      39,   163,    13,    32,   136,    39,    37,    38,   133,    33,
      34,    35,    33,    34,    35,    98,   108,     0,    36,    39,
     153,    36,   109,     0,     0,     0,    37,    38,     0,    37,
      38,     0,     0,     0,     0,     0,     0,     0,     0,    39,
       0,     0,    39
};

static const yytype_int16 yycheck[] =
{
      24,    25,     0,    56,    52,     5,     4,     5,    37,    38,
      39,    12,    36,    27,   122,     5,    17,    31,    19,   155,
     156,     3,     4,     5,    11,    13,    50,   163,    16,    16,
      12,    12,    14,    15,    13,    59,    60,    16,    20,    21,
      54,    17,    90,    19,    58,   153,     0,     5,    77,    78,
      79,    33,     6,     7,    52,     9,    10,    81,    82,    14,
       3,     4,     5,     6,     7,     8,     5,    10,    11,    12,
      18,    14,    15,    13,    31,    99,    16,    20,    21,     3,
       4,     5,   106,   136,    22,    23,    24,    32,    12,    13,
      33,    34,    90,    36,    37,    38,    20,    21,   122,     6,
       7,    17,    14,    19,   128,   129,    13,   155,   156,    33,
      13,   135,     6,     7,   138,   163,    12,     6,     7,    13,
     144,    17,    17,     3,     4,     5,     6,     7,     8,   153,
      10,    11,    12,     0,    14,    15,    20,    21,     5,    17,
      20,    21,    25,    26,    27,    28,    29,    30,     6,     7,
      11,     9,    10,    33,    34,    16,    36,    37,    38,     3,
       4,     5,    15,    16,     8,    15,    16,    11,    12,    18,
      14,    12,    15,    16,    75,    76,    20,    21,    69,    70,
      71,    72,    73,    74,    12,    11,     3,     4,     5,    33,
      34,    11,    36,    37,    38,    12,    11,    14,    15,    17,
       3,     4,     5,    20,    21,     3,     4,     5,    19,    12,
      18,    14,    15,    11,    12,    11,    33,    20,    21,     3,
       4,     5,    20,    21,    17,    13,    18,    13,    12,    11,
      33,    35,     5,    23,    18,    33,    20,    21,    90,     3,
       4,     5,     3,     4,     5,    55,    67,    -1,    12,    33,
      14,    12,    68,    -1,    -1,    -1,    20,    21,    -1,    20,
      21,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    33,
      -1,    -1,    33
};

/* YYSTOS[STATE-NUM] -- The symbol kind of the accessing symbol of
   state STATE-NUM.  */
static const yytype_int8 yystos[] =
{
       0,     6,     7,     9,    10,    41,    42,    48,    49,    54,
       5,    54,     0,    42,    48,    11,    16,     5,    52,    12,
       5,    52,    52,    12,    17,    19,    50,    13,    43,    44,
      54,    13,    43,     3,     4,     5,    12,    20,    21,    33,
      56,    57,    58,    59,    60,    61,    62,    63,    65,    56,
      17,    19,    14,    45,    13,    16,     5,    45,    13,    12,
      17,    51,    56,    62,    62,    62,    18,    32,    31,    25,
      26,    27,    28,    29,    30,    20,    21,    22,    23,    24,
      56,    14,     8,    11,    15,    34,    36,    37,    38,    45,
      46,    47,    48,    54,    55,    56,    65,    45,    44,    17,
      50,    45,    13,    56,    64,    56,    17,    13,    58,    59,
      60,    60,    60,    60,    60,    60,    61,    61,    62,    62,
      62,    18,    14,    15,    53,    56,    11,    56,    12,    12,
      11,    11,    15,    47,    11,    19,    18,    13,    16,    18,
      56,    15,    53,    15,    16,    11,    56,    56,    56,    50,
      56,    18,    15,    14,    56,    13,    13,    11,    15,    53,
      55,    55,    15,    35,    55
};

/* YYR1[RULE-NUM] -- Symbol kind of the left-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr1[] =
{
       0,    40,    41,    41,    41,    41,    42,    42,    42,    42,
      43,    43,    44,    44,    44,    44,    45,    45,    46,    46,
      47,    47,    48,    49,    49,    49,    50,    50,    51,    51,
      52,    52,    52,    52,    52,    53,    53,    53,    53,    53,
      53,    54,    54,    55,    55,    55,    55,    55,    55,    55,
      55,    55,    55,    55,    56,    57,    57,    58,    58,    59,
      59,    59,    59,    59,    59,    59,    60,    60,    60,    61,
      61,    61,    61,    62,    62,    62,    62,    62,    62,    63,
      63,    63,    63,    64,    64,    65,    65
};

/* YYR2[RULE-NUM] -- Number of symbols on the right-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr2[] =
{
       0,     2,     1,     1,     2,     2,     5,     6,     5,     6,
       1,     3,     2,     3,     4,     5,     2,     3,     1,     2,
       1,     1,     2,     2,     3,     3,     3,     4,     3,     4,
       1,     2,     3,     5,     6,     1,     3,     3,     2,     5,
       4,     1,     1,     3,     2,     4,     1,     2,     1,     5,
       7,     5,     2,     2,     1,     1,     3,     1,     3,     1,
       3,     3,     3,     3,     3,     3,     1,     3,     3,     1,
       3,     3,     3,     1,     3,     4,     2,     2,     2,     3,
       1,     1,     1,     1,     3,     1,     2
};


enum { YYENOMEM = -2 };

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (yychar = YYEMPTY)

#define YYACCEPT        goto yyacceptlab
#define YYABORT         goto yyabortlab
#define YYERROR         goto yyerrorlab
#define YYNOMEM         goto yyexhaustedlab


#define YYRECOVERING()  (!!yyerrstatus)

#define YYBACKUP(Token, Value)                                    \
  do                                                              \
    if (yychar == YYEMPTY)                                        \
      {                                                           \
        yychar = (Token);                                         \
        yylval = (Value);                                         \
        YYPOPSTACK (yylen);                                       \
        yystate = *yyssp;                                         \
        goto yybackup;                                            \
      }                                                           \
    else                                                          \
      {                                                           \
        yyerror (YY_("syntax error: cannot back up")); \
        YYERROR;                                                  \
      }                                                           \
  while (0)

/* Backward compatibility with an undocumented macro.
   Use YYerror or YYUNDEF. */
#define YYERRCODE YYUNDEF


/* Enable debugging if requested.  */
#if YYDEBUG

# ifndef YYFPRINTF
#  include <stdio.h> /* INFRINGES ON USER NAME SPACE */
#  define YYFPRINTF fprintf
# endif

# define YYDPRINTF(Args)                        \
do {                                            \
  if (yydebug)                                  \
    YYFPRINTF Args;                             \
} while (0)




# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)                    \
do {                                                                      \
  if (yydebug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      yy_symbol_print (stderr,                                            \
                  Kind, Value); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (0)


/*-----------------------------------.
| Print this symbol's value on YYO.  |
`-----------------------------------*/

static void
yy_symbol_value_print (FILE *yyo,
                       yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  FILE *yyoutput = yyo;
  YY_USE (yyoutput);
  if (!yyvaluep)
    return;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/*---------------------------.
| Print this symbol on YYO.  |
`---------------------------*/

static void
yy_symbol_print (FILE *yyo,
                 yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  YYFPRINTF (yyo, "%s %s (",
             yykind < YYNTOKENS ? "token" : "nterm", yysymbol_name (yykind));

  yy_symbol_value_print (yyo, yykind, yyvaluep);
  YYFPRINTF (yyo, ")");
}

/*------------------------------------------------------------------.
| yy_stack_print -- Print the state stack from its BOTTOM up to its |
| TOP (included).                                                   |
`------------------------------------------------------------------*/

static void
yy_stack_print (yy_state_t *yybottom, yy_state_t *yytop)
{
  YYFPRINTF (stderr, "Stack now");
  for (; yybottom <= yytop; yybottom++)
    {
      int yybot = *yybottom;
      YYFPRINTF (stderr, " %d", yybot);
    }
  YYFPRINTF (stderr, "\n");
}

# define YY_STACK_PRINT(Bottom, Top)                            \
do {                                                            \
  if (yydebug)                                                  \
    yy_stack_print ((Bottom), (Top));                           \
} while (0)


/*------------------------------------------------.
| Report that the YYRULE is going to be reduced.  |
`------------------------------------------------*/

static void
yy_reduce_print (yy_state_t *yyssp, YYSTYPE *yyvsp,
                 int yyrule)
{
  int yylno = yyrline[yyrule];
  int yynrhs = yyr2[yyrule];
  int yyi;
  YYFPRINTF (stderr, "Reducing stack by rule %d (line %d):\n",
             yyrule - 1, yylno);
  /* The symbols being reduced.  */
  for (yyi = 0; yyi < yynrhs; yyi++)
    {
      YYFPRINTF (stderr, "   $%d = ", yyi + 1);
      yy_symbol_print (stderr,
                       YY_ACCESSING_SYMBOL (+yyssp[yyi + 1 - yynrhs]),
                       &yyvsp[(yyi + 1) - (yynrhs)]);
      YYFPRINTF (stderr, "\n");
    }
}

# define YY_REDUCE_PRINT(Rule)          \
do {                                    \
  if (yydebug)                          \
    yy_reduce_print (yyssp, yyvsp, Rule); \
} while (0)

/* Nonzero means print parse trace.  It is left uninitialized so that
   multiple parsers can coexist.  */
int yydebug;
#else /* !YYDEBUG */
# define YYDPRINTF(Args) ((void) 0)
# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)
# define YY_STACK_PRINT(Bottom, Top)
# define YY_REDUCE_PRINT(Rule)
#endif /* !YYDEBUG */


/* YYINITDEPTH -- initial size of the parser's stacks.  */
#ifndef YYINITDEPTH
# define YYINITDEPTH 200
#endif

/* YYMAXDEPTH -- maximum size the stacks can grow to (effective only
   if the built-in stack extension method is used).

   Do not make this value too large; the results are undefined if
   YYSTACK_ALLOC_MAXIMUM < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

#ifndef YYMAXDEPTH
# define YYMAXDEPTH 10000
#endif






/*-----------------------------------------------.
| Release the memory associated to this symbol.  |
`-----------------------------------------------*/

static void
yydestruct (const char *yymsg,
            yysymbol_kind_t yykind, YYSTYPE *yyvaluep)
{
  YY_USE (yyvaluep);
  if (!yymsg)
    yymsg = "Deleting";
  YY_SYMBOL_PRINT (yymsg, yykind, yyvaluep, yylocationp);

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/* Lookahead token kind.  */
int yychar;

/* The semantic value of the lookahead symbol.  */
YYSTYPE yylval;
/* Number of syntax errors so far.  */
int yynerrs;




/*----------.
| yyparse.  |
`----------*/

int
yyparse (void)
{
    yy_state_fast_t yystate = 0;
    /* Number of tokens to shift before error messages enabled.  */
    int yyerrstatus = 0;

    /* Refer to the stacks through separate pointers, to allow yyoverflow
       to reallocate them elsewhere.  */

    /* Their size.  */
    YYPTRDIFF_T yystacksize = YYINITDEPTH;

    /* The state stack: array, bottom, top.  */
    yy_state_t yyssa[YYINITDEPTH];
    yy_state_t *yyss = yyssa;
    yy_state_t *yyssp = yyss;

    /* The semantic value stack: array, bottom, top.  */
    YYSTYPE yyvsa[YYINITDEPTH];
    YYSTYPE *yyvs = yyvsa;
    YYSTYPE *yyvsp = yyvs;

  int yyn;
  /* The return value of yyparse.  */
  int yyresult;
  /* Lookahead symbol kind.  */
  yysymbol_kind_t yytoken = YYSYMBOL_YYEMPTY;
  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;



#define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))

  /* The number of symbols on the RHS of the reduced rule.
     Keep to zero when no symbol should be popped.  */
  int yylen = 0;

  YYDPRINTF ((stderr, "Starting parse\n"));

  yychar = YYEMPTY; /* Cause a token to be read.  */

  goto yysetstate;


/*------------------------------------------------------------.
| yynewstate -- push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed.  So pushing a state here evens the stacks.  */
  yyssp++;


/*--------------------------------------------------------------------.
| yysetstate -- set current state (the top of the stack) to yystate.  |
`--------------------------------------------------------------------*/
yysetstate:
  YYDPRINTF ((stderr, "Entering state %d\n", yystate));
  YY_ASSERT (0 <= yystate && yystate < YYNSTATES);
  YY_IGNORE_USELESS_CAST_BEGIN
  *yyssp = YY_CAST (yy_state_t, yystate);
  YY_IGNORE_USELESS_CAST_END
  YY_STACK_PRINT (yyss, yyssp);

  if (yyss + yystacksize - 1 <= yyssp)
#if !defined yyoverflow && !defined YYSTACK_RELOCATE
    YYNOMEM;
#else
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYPTRDIFF_T yysize = yyssp - yyss + 1;

# if defined yyoverflow
      {
        /* Give user a chance to reallocate the stack.  Use copies of
           these so that the &'s don't force the real ones into
           memory.  */
        yy_state_t *yyss1 = yyss;
        YYSTYPE *yyvs1 = yyvs;

        /* Each stack pointer address is followed by the size of the
           data in use in that stack, in bytes.  This used to be a
           conditional around just the two extra args, but that might
           be undefined if yyoverflow is a macro.  */
        yyoverflow (YY_("memory exhausted"),
                    &yyss1, yysize * YYSIZEOF (*yyssp),
                    &yyvs1, yysize * YYSIZEOF (*yyvsp),
                    &yystacksize);
        yyss = yyss1;
        yyvs = yyvs1;
      }
# else /* defined YYSTACK_RELOCATE */
      /* Extend the stack our own way.  */
      if (YYMAXDEPTH <= yystacksize)
        YYNOMEM;
      yystacksize *= 2;
      if (YYMAXDEPTH < yystacksize)
        yystacksize = YYMAXDEPTH;

      {
        yy_state_t *yyss1 = yyss;
        union yyalloc *yyptr =
          YY_CAST (union yyalloc *,
                   YYSTACK_ALLOC (YY_CAST (YYSIZE_T, YYSTACK_BYTES (yystacksize))));
        if (! yyptr)
          YYNOMEM;
        YYSTACK_RELOCATE (yyss_alloc, yyss);
        YYSTACK_RELOCATE (yyvs_alloc, yyvs);
#  undef YYSTACK_RELOCATE
        if (yyss1 != yyssa)
          YYSTACK_FREE (yyss1);
      }
# endif

      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;

      YY_IGNORE_USELESS_CAST_BEGIN
      YYDPRINTF ((stderr, "Stack size increased to %ld\n",
                  YY_CAST (long, yystacksize)));
      YY_IGNORE_USELESS_CAST_END

      if (yyss + yystacksize - 1 <= yyssp)
        YYABORT;
    }
#endif /* !defined yyoverflow && !defined YYSTACK_RELOCATE */


  if (yystate == YYFINAL)
    YYACCEPT;

  goto yybackup;


/*-----------.
| yybackup.  |
`-----------*/
yybackup:
  /* Do appropriate processing given the current state.  Read a
     lookahead token if we need one and don't already have one.  */

  /* First try to decide what to do without reference to lookahead token.  */
  yyn = yypact[yystate];
  if (yypact_value_is_default (yyn))
    goto yydefault;

  /* Not known => get a lookahead token if don't already have one.  */

  /* YYCHAR is either empty, or end-of-input, or a valid lookahead.  */
  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token\n"));
      yychar = yylex ();
    }

  if (yychar <= YYEOF)
    {
      yychar = YYEOF;
      yytoken = YYSYMBOL_YYEOF;
      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else if (yychar == YYerror)
    {
      /* The scanner already issued an error message, process directly
         to error recovery.  But do not keep the error token as
         lookahead, it is too special and may lead us to an endless
         loop in error recovery. */
      yychar = YYUNDEF;
      yytoken = YYSYMBOL_YYerror;
      goto yyerrlab1;
    }
  else
    {
      yytoken = YYTRANSLATE (yychar);
      YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
    }

  /* If the proper action on seeing token YYTOKEN is to reduce or to
     detect an error, take that action.  */
  yyn += yytoken;
  if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
    goto yydefault;
  yyn = yytable[yyn];
  if (yyn <= 0)
    {
      if (yytable_value_is_error (yyn))
        goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }

  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;

  /* Shift the lookahead token.  */
  YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
  yystate = yyn;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END

  /* Discard the shifted token.  */
  yychar = YYEMPTY;
  goto yynewstate;


/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;


/*-----------------------------.
| yyreduce -- do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];

  /* If YYLEN is nonzero, implement the default value of the action:
     '$$ = $1'.

     Otherwise, the following line sets YYVAL to garbage.
     This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];


  YY_REDUCE_PRINT (yyn);
  switch (yyn)
    {
  case 2: /* CompileUnit: FuncDef  */
#line 103 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                      {

		// 创建一个编译单元的节点AST_OP_COMPILE_UNIT
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));

		// 设置到全局变量中
		ast_root = (yyval.node);
	}
#line 1280 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 3: /* CompileUnit: VarDecl  */
#line 111 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                  {

		// 创建一个编译单元的节点AST_OP_COMPILE_UNIT
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));
		ast_root = (yyval.node);
	}
#line 1291 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 4: /* CompileUnit: CompileUnit FuncDef  */
#line 117 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                              {

		// 把函数定义的节点作为编译单元的孩子
		(yyval.node) = (yyvsp[-1].node)->insert_son_node((yyvsp[0].node));
	}
#line 1301 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 5: /* CompileUnit: CompileUnit VarDecl  */
#line 122 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                              {
		// 把变量定义的节点作为编译单元的孩子
		(yyval.node) = (yyvsp[-1].node)->insert_son_node((yyvsp[0].node));
	}
#line 1310 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 6: /* FuncDef: BasicType T_ID T_L_PAREN T_R_PAREN Block  */
#line 129 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                                    {

		// 函数返回类型
		type_attr funcReturnType = (yyvsp[-4].type);

		// 函数名
		var_id_attr funcId = (yyvsp[-3].var_id);

		// 函数体节点即Block，即$5
		ast_node * blockNode = (yyvsp[0].node);

		// 形参结点没有，设置为空指针
		ast_node * formalParamsNode = nullptr;

		// 创建函数定义的节点，孩子有类型，函数名，语句块和形参(实际上无)
		// create_func_def函数内会释放funcId中指向的标识符空间，切记，之后不要再释放，之前一定要是通过strdup函数或者malloc分配的空间
		(yyval.node) = create_func_def(funcReturnType, funcId, blockNode, formalParamsNode);
	}
#line 1333 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 7: /* FuncDef: BasicType T_ID T_L_PAREN FormalParams T_R_PAREN Block  */
#line 147 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                                                {
		// 函数返回类型
		type_attr funcReturnType = (yyvsp[-5].type);

		// 函数名
		var_id_attr funcId = (yyvsp[-4].var_id);

		// 函数体节点即Block，即$6
		ast_node * blockNode = (yyvsp[0].node);

		// 形参结点，即$4
		ast_node * formalParamsNode = (yyvsp[-2].node);

		// 创建函数定义的节点，孩子有类型，函数名，语句块和形参
		(yyval.node) = create_func_def(funcReturnType, funcId, blockNode, formalParamsNode);
	}
#line 1354 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 8: /* FuncDef: T_VOID T_ID T_L_PAREN T_R_PAREN Block  */
#line 163 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                                {
		// 函数返回类型为void
		type_attr funcReturnType;
		funcReturnType.type = BasicType::TYPE_VOID;
		funcReturnType.lineno = yylineno;

		// 函数名
		var_id_attr funcId = (yyvsp[-3].var_id);

		// 函数体节点即Block，即$5
		ast_node * blockNode = (yyvsp[0].node);

		// 形参结点没有，设置为空指针
		ast_node * formalParamsNode = nullptr;

		// 创建函数定义的节点，孩子有类型，函数名，语句块和形参(实际上无)
		(yyval.node) = create_func_def(funcReturnType, funcId, blockNode, formalParamsNode);
	}
#line 1377 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 9: /* FuncDef: T_VOID T_ID T_L_PAREN FormalParams T_R_PAREN Block  */
#line 181 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                                             {
		// 函数返回类型为void
		type_attr funcReturnType;
		funcReturnType.type = BasicType::TYPE_VOID;
		funcReturnType.lineno = yylineno;

		// 函数名
		var_id_attr funcId = (yyvsp[-4].var_id);

		// 函数体节点即Block，即$6
		ast_node * blockNode = (yyvsp[0].node);

		// 形参结点，即$4
		ast_node * formalParamsNode = (yyvsp[-2].node);

		// 创建函数定义的节点，孩子有类型，函数名，语句块和形参
		(yyval.node) = create_func_def(funcReturnType, funcId, blockNode, formalParamsNode);
	}
#line 1400 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 10: /* FormalParams: FormalParam  */
#line 202 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                           {
		// 创建形参列表节点，并把当前的形参节点加入
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_FORMAL_PARAMS, (yyvsp[0].node));
	}
#line 1409 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 11: /* FormalParams: FormalParams T_COMMA FormalParam  */
#line 206 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                           {
		// 左递归增加形参
		(yyval.node) = (yyvsp[-2].node)->insert_son_node((yyvsp[0].node));
	}
#line 1418 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 12: /* FormalParam: BasicType T_ID  */
#line 213 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                             {
		// 创建形参节点
		(yyval.node) = create_func_formal_param((yyvsp[-1].type), (yyvsp[0].var_id));
	}
#line 1427 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 13: /* FormalParam: BasicType T_ID ArrayDims  */
#line 217 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                   {
		// 创建数组形参节点
		var_id_attr id = (yyvsp[-1].var_id);
		ast_node* id_node = ast_node::New(id);
		free(id.id);

		// 获取基本类型
		Type* baseType = typeAttr2Type((yyvsp[-2].type));
		
		// 创建数组形参节点
		(yyval.node) = createArrayParamNode(baseType, id_node, (yyvsp[0].node));
	}
#line 1444 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 14: /* FormalParam: BasicType T_ID T_L_BRACKET T_R_BRACKET  */
#line 229 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                                 {
		// 创建简化形式的数组形参节点 int a[]
		var_id_attr id = (yyvsp[-2].var_id);
		ast_node* id_node = ast_node::New(id);
		free(id.id);

		// 获取基本类型
		Type* baseType = typeAttr2Type((yyvsp[-3].type));
		
		// 创建一个空的维度节点
		ast_node* empty_dims = create_contain_node(ast_operator_type::AST_OP_ARRAY_DIMS);
		
		// 添加一个维度，保留原始维度值
		digit_int_attr dim_attr;
		dim_attr.val = 0; // 使用一个合理的默认值
		dim_attr.lineno = yylineno;
		ast_node* dim_node = ast_node::New(dim_attr);
		empty_dims->insert_son_node(dim_node);
		
		// 创建数组形参节点
		(yyval.node) = createArrayParamNode(baseType, id_node, empty_dims);
	}
#line 1471 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 15: /* FormalParam: BasicType T_ID T_L_BRACKET T_R_BRACKET ArrayDims  */
#line 251 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                                           {
		// 创建多维数组形参节点 int a[][2][3]
		var_id_attr id = (yyvsp[-3].var_id);
		ast_node* id_node = ast_node::New(id);
		free(id.id);

		// 获取基本类型
		Type* baseType = typeAttr2Type((yyvsp[-4].type));
		
		// 创建一个维度节点，保留原始维度值
		ast_node* array_dims = create_contain_node(ast_operator_type::AST_OP_ARRAY_DIMS);
		
		// 添加一个维度，保留原始维度值
		digit_int_attr dim_attr;
		dim_attr.val = 0; // 使用一个合理的默认值
		dim_attr.lineno = yylineno;
		ast_node* dim_node = ast_node::New(dim_attr);
		array_dims->insert_son_node(dim_node);
		
		// 将其他维度添加到维度节点
		for (auto& son : (yyvsp[0].node)->sons) {
			array_dims->insert_son_node(son);
		}
		
		// 创建数组形参节点
		(yyval.node) = createArrayParamNode(baseType, id_node, array_dims);
	}
#line 1503 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 16: /* Block: T_L_BRACE T_R_BRACE  */
#line 283 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                            {
		// 语句块没有语句

		// 为了方便创建一个空的Block节点
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_BLOCK);
	}
#line 1514 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 17: /* Block: T_L_BRACE BlockItemList T_R_BRACE  */
#line 289 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                            {
		// 语句块含有语句

		// BlockItemList归约时内部创建Block节点，并把语句加入，这里不创建Block节点
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1525 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 18: /* BlockItemList: BlockItem  */
#line 300 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                          {
		// 第一个左侧的孩子节点归约成Block节点，后续语句可持续作为孩子追加到Block节点中
		// 创建一个AST_OP_BLOCK类型的中间节点，孩子为Statement($1)
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_BLOCK, (yyvsp[0].node));
	}
#line 1535 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 19: /* BlockItemList: BlockItemList BlockItem  */
#line 305 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                  {
		// 把BlockItem归约的节点加入到BlockItemList的节点中
		(yyval.node) = (yyvsp[-1].node)->insert_son_node((yyvsp[0].node));
	}
#line 1544 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 20: /* BlockItem: Statement  */
#line 314 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                       {
		// 语句节点传递给归约后的节点上，综合属性
		(yyval.node) = (yyvsp[0].node);
	}
#line 1553 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 21: /* BlockItem: VarDecl  */
#line 318 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                  {
		// 变量声明节点传递给归约后的节点上，综合属性
		(yyval.node) = (yyvsp[0].node);
	}
#line 1562 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 22: /* VarDecl: VarDeclExpr T_SEMICOLON  */
#line 329 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                  {
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1570 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 23: /* VarDeclExpr: BasicType VarDef  */
#line 335 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                              {
		// 创建类型节点
		ast_node * type_node = create_type_node((yyvsp[-1].type));
		Type * type = typeAttr2Type((yyvsp[-1].type));

		// 创建变量定义节点
		ast_node * decl_node;
		
		// 判断VarDef是否为带初始化的变量定义，或者是数组定义
		if ((yyvsp[0].node)->node_type == ast_operator_type::AST_OP_VAR_DEF_INIT) {
			// 如果是带初始化的变量定义，保持其节点结构
			decl_node = create_contain_node(ast_operator_type::AST_OP_VAR_DECL, type_node, (yyvsp[0].node));
		} else if ((yyvsp[0].node)->node_type == ast_operator_type::AST_OP_ARRAY_DIMS) {
			// 如果是数组定义
			// 获取数组维度节点
			ast_node* dims_node = (yyvsp[0].node);
			// 获取ID节点（添加为数组维度的子节点）
			ast_node* id_node = dims_node->sons.back();
			// 移除ID节点
			dims_node->sons.pop_back();
			
			// 创建数组定义节点
			ast_node* array_def_node = createArrayDefNode(type, id_node, dims_node);
			
			// 创建变量声明节点
			decl_node = create_contain_node(ast_operator_type::AST_OP_VAR_DECL, type_node, array_def_node);
		} else {
			// 如果是普通变量定义，创建普通的变量声明节点
			decl_node = create_contain_node(ast_operator_type::AST_OP_VAR_DECL, type_node, (yyvsp[0].node));
		}
		
		decl_node->type = type;
		decl_node->is_const = false; // 非const变量

		// 创建变量声明语句，并加入第一个变量
		(yyval.node) = create_var_decl_stmt_node(decl_node);
	}
#line 1612 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 24: /* VarDeclExpr: T_CONST BasicType VarDef  */
#line 372 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                   {
		// 创建类型节点
		ast_node * type_node = create_type_node((yyvsp[-1].type));
		Type * type = typeAttr2Type((yyvsp[-1].type));

		// 创建变量定义节点
		ast_node * decl_node;
		
		// 判断VarDef是否为带初始化的变量定义，或者是数组定义
		if ((yyvsp[0].node)->node_type == ast_operator_type::AST_OP_VAR_DEF_INIT) {
			// 如果是带初始化的变量定义，保持其节点结构
			decl_node = create_contain_node(ast_operator_type::AST_OP_VAR_DECL, type_node, (yyvsp[0].node));
		} else if ((yyvsp[0].node)->node_type == ast_operator_type::AST_OP_ARRAY_DIMS) {
			// 如果是数组定义
			// 获取数组维度节点
			ast_node* dims_node = (yyvsp[0].node);
			// 获取ID节点（添加为数组维度的子节点）
			ast_node* id_node = dims_node->sons.back();
			// 移除ID节点
			dims_node->sons.pop_back();
			
			// 创建数组定义节点
			ast_node* array_def_node = createArrayDefNode(type, id_node, dims_node);
			
			// 创建变量声明节点
			decl_node = create_contain_node(ast_operator_type::AST_OP_VAR_DECL, type_node, array_def_node);
		} else {
			// 如果是普通变量定义，创建普通的变量声明节点
			decl_node = create_contain_node(ast_operator_type::AST_OP_VAR_DECL, type_node, (yyvsp[0].node));
		}
		
		decl_node->type = type;
		decl_node->is_const = true; // 标记为const变量

		// 创建变量声明语句，并加入第一个变量
		(yyval.node) = create_var_decl_stmt_node(decl_node);
	}
#line 1654 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 25: /* VarDeclExpr: VarDeclExpr T_COMMA VarDef  */
#line 409 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                     {
		// 获取类型，这里从VarDeclExpr获取类型，前面已经设置
		Type * type = (yyvsp[-2].node)->type;
		ast_node * type_node = ast_node::New(type);
		bool is_const = (yyvsp[-2].node)->sons[0]->is_const; // 传递const属性

		// 创建变量定义节点
		ast_node * decl_node;
		
		// 判断VarDef是否为带初始化的变量定义，或者是数组定义
		if ((yyvsp[0].node)->node_type == ast_operator_type::AST_OP_VAR_DEF_INIT) {
			// 如果是带初始化的变量定义，保持其节点结构
			decl_node = create_contain_node(ast_operator_type::AST_OP_VAR_DECL, type_node, (yyvsp[0].node));
		} else if ((yyvsp[0].node)->node_type == ast_operator_type::AST_OP_ARRAY_DIMS) {
			// 如果是数组定义
			// 获取数组维度节点
			ast_node* dims_node = (yyvsp[0].node);
			// 获取ID节点（添加为数组维度的子节点）
			ast_node* id_node = dims_node->sons.back();
			// 移除ID节点
			dims_node->sons.pop_back();
			
			// 创建数组定义节点
			ast_node* array_def_node = createArrayDefNode(type, id_node, dims_node);
			
			// 创建变量声明节点
			decl_node = create_contain_node(ast_operator_type::AST_OP_VAR_DECL, type_node, array_def_node);
		} else {
			// 如果是普通变量定义，创建普通的变量声明节点
			decl_node = create_contain_node(ast_operator_type::AST_OP_VAR_DECL, type_node, (yyvsp[0].node));
		}
		
		decl_node->type = type;
		decl_node->is_const = is_const; // 保持与前面变量相同的const属性

		// 插入到变量声明语句
		(yyval.node) = (yyvsp[-2].node)->insert_son_node(decl_node);
	}
#line 1697 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 26: /* ArrayDims: T_L_BRACKET Expr T_R_BRACKET  */
#line 450 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                         {
		// 创建数组维度节点
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_ARRAY_DIMS, (yyvsp[-1].node));
	}
#line 1706 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 27: /* ArrayDims: ArrayDims T_L_BRACKET Expr T_R_BRACKET  */
#line 454 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                                 {
		// 添加新的维度
		(yyval.node) = (yyvsp[-3].node)->insert_son_node((yyvsp[-1].node));
	}
#line 1715 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 28: /* ArrayIndices: T_L_BRACKET Expr T_R_BRACKET  */
#line 461 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                            {
		// 创建数组索引节点
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_ARRAY_INDICES, (yyvsp[-1].node));
	}
#line 1724 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 29: /* ArrayIndices: ArrayIndices T_L_BRACKET Expr T_R_BRACKET  */
#line 465 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                                    {
		// 添加新的索引
		(yyval.node) = (yyvsp[-3].node)->insert_son_node((yyvsp[-1].node));
	}
#line 1733 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 30: /* VarDef: T_ID  */
#line 472 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
              {
		// 变量ID

		// 创建变量ID节点
		ast_node * id_node = ast_node::New(var_id_attr{(yyvsp[0].var_id).id, (yyvsp[0].var_id).lineno});

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[0].var_id).id);
		
		// 创建不带初始化的变量定义节点
		(yyval.node) = id_node;
	}
#line 1750 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 31: /* VarDef: T_ID ArrayDims  */
#line 484 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                         {
		// 数组变量定义

		// 创建变量ID节点
		ast_node * id_node = ast_node::New(var_id_attr{(yyvsp[-1].var_id).id, (yyvsp[-1].var_id).lineno});

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[-1].var_id).id);
		
		// 创建数组变量定义节点
		(yyval.node) = createArrayDefNode(IntegerType::getTypeInt(), id_node, (yyvsp[0].node));
	}
#line 1767 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 32: /* VarDef: T_ID T_ASSIGN Expr  */
#line 496 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                             {
		// 变量ID和初始化表达式

		// 创建变量ID节点
		ast_node * id_node = ast_node::New(var_id_attr{(yyvsp[-2].var_id).id, (yyvsp[-2].var_id).lineno});

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[-2].var_id).id);

		// 创建带初始化的变量定义节点
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_VAR_DEF_INIT, id_node, (yyvsp[0].node));
	}
#line 1784 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 33: /* VarDef: T_ID ArrayDims T_ASSIGN T_L_BRACE T_R_BRACE  */
#line 508 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                                      {
		// 空数组初始化 int a[4][2] = {}

		// 创建变量ID节点
		ast_node * id_node = ast_node::New(var_id_attr{(yyvsp[-4].var_id).id, (yyvsp[-4].var_id).lineno});

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[-4].var_id).id);
		
		// 创建空初始化列表节点
		ast_node * empty_init = create_contain_node(ast_operator_type::AST_OP_ARRAY_INIT_EMPTY);
		
		// 创建数组变量定义节点
		ast_node * array_def = createArrayDefNode(IntegerType::getTypeInt(), id_node, (yyvsp[-3].node));
		
		// 添加空初始化列表作为子节点
		array_def->insert_son_node(empty_init);
		
		(yyval.node) = array_def;
	}
#line 1809 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 34: /* VarDef: T_ID ArrayDims T_ASSIGN T_L_BRACE ArrayInitList T_R_BRACE  */
#line 528 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                                                    {
		// 带初始化的数组定义 int a[4][2] = {1, 2, 3, 4, 5, 6, 7, 8}

		// 创建变量ID节点
		ast_node * id_node = ast_node::New(var_id_attr{(yyvsp[-5].var_id).id, (yyvsp[-5].var_id).lineno});

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[-5].var_id).id);
		
		// 创建数组变量定义节点
		ast_node * array_def = createArrayDefNode(IntegerType::getTypeInt(), id_node, (yyvsp[-4].node));
		
		// 添加初始化列表作为子节点
		array_def->insert_son_node((yyvsp[-1].node));
		
		(yyval.node) = array_def;
	}
#line 1831 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 35: /* ArrayInitList: Expr  */
#line 548 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                     {
		// 创建初始化列表节点，并添加第一个表达式
		ast_node * init_list = create_contain_node(ast_operator_type::AST_OP_ARRAY_INIT_LIST);
		if((yyvsp[0].node) == nullptr){
			ast_node * init = new ast_node(ast_operator_type::AST_OP_LEAF_LITERAL_UINT, IntegerType::getTypeInt(),-1);
			init ->integer_val = 0;
			ast_node * elem = create_contain_node(ast_operator_type::AST_OP_ARRAY_INIT_ELEM, init);
			init_list->insert_son_node(elem);
		}else {
			ast_node * elem = create_contain_node(ast_operator_type::AST_OP_ARRAY_INIT_ELEM, (yyvsp[0].node));
			init_list->insert_son_node(elem);
		}
	
		(yyval.node) = init_list;
	}
#line 1851 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 36: /* ArrayInitList: ArrayInitList T_COMMA Expr  */
#line 563 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                     {
		// 添加更多的初始化表达式
		ast_node * elem = create_contain_node(ast_operator_type::AST_OP_ARRAY_INIT_ELEM, (yyvsp[0].node));
		(yyvsp[-2].node)->insert_son_node(elem);
		(yyval.node) = (yyvsp[-2].node);
	}
#line 1862 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 37: /* ArrayInitList: T_L_BRACE ArrayInitList T_R_BRACE  */
#line 569 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                            {
		// 嵌套初始化列表 例如 {{1, 2}, {3, 4}}
		//$$ = $2;
		// 修复1：嵌套列表作为单个元素
        ast_node* list_wrapper = create_contain_node(ast_operator_type::AST_OP_ARRAY_INIT_LIST, (yyvsp[-1].node));
        (yyval.node) = list_wrapper;  // 返回包装后的元素节点
	}
#line 1874 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 38: /* ArrayInitList: T_L_BRACE T_R_BRACE  */
#line 576 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                              {
		// 嵌套初始化列表 例如 {{1, 2}, {3, 4}}
		// 修复2：嵌套空列表作为单个元素
		ast_node * init_list = create_contain_node(ast_operator_type::AST_OP_ARRAY_INIT_LIST);
		ast_node * init = new ast_node(ast_operator_type::AST_OP_LEAF_LITERAL_UINT, IntegerType::getTypeInt(),-1);
		init ->integer_val = 0;
		ast_node * elem = create_contain_node(ast_operator_type::AST_OP_ARRAY_INIT_ELEM, init);
		init_list->insert_son_node(elem);
		
		ast_node* list_wrapper = create_contain_node(ast_operator_type::AST_OP_ARRAY_INIT_LIST, init_list);
        (yyval.node) = list_wrapper;  // 返回包装后的元素节点
	}
#line 1891 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 39: /* ArrayInitList: ArrayInitList T_COMMA T_L_BRACE ArrayInitList T_R_BRACE  */
#line 588 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                                                  {
		// 嵌套初始化列表后跟更多元素 例如 {1, 2, {3}, {5}}
		(yyvsp[-4].node)->insert_son_node((yyvsp[-1].node));
		(yyval.node) = (yyvsp[-4].node);
	}
#line 1901 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 40: /* ArrayInitList: ArrayInitList T_COMMA T_L_BRACE T_R_BRACE  */
#line 593 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                                     {
		// 嵌套初始化列表后跟更多元素 例如 {1, 2, {3}, {5}}
		// 修复2：嵌套空列表作为单个元素
		ast_node * init_list = create_contain_node(ast_operator_type::AST_OP_ARRAY_INIT_LIST);
		ast_node * init = new ast_node(ast_operator_type::AST_OP_LEAF_LITERAL_UINT, IntegerType::getTypeInt(),-1);
		init ->integer_val = 0;
		ast_node * elem = create_contain_node(ast_operator_type::AST_OP_ARRAY_INIT_ELEM, init);
		init_list->insert_son_node(elem);
		(yyvsp[-3].node)->insert_son_node(init_list);
		(yyval.node) = (yyvsp[-3].node);
	}
#line 1917 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 41: /* BasicType: T_INT  */
#line 607 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                 {
		(yyval.type) = (yyvsp[0].type);
	}
#line 1925 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 42: /* BasicType: T_FLOAT  */
#line 610 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                  {
		(yyval.type) = (yyvsp[0].type);
	}
#line 1933 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 43: /* Statement: T_RETURN Expr T_SEMICOLON  */
#line 619 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                      {
		// 返回语句

		// 创建返回节点AST_OP_RETURN，其孩子为Expr，即$2
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_RETURN, (yyvsp[-1].node));
	}
#line 1944 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 44: /* Statement: T_RETURN T_SEMICOLON  */
#line 625 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                               {
		// 不带表达式的返回语句

		// 创建不带表达式的返回节点AST_OP_RETURN
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_RETURN);
	}
#line 1955 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 45: /* Statement: LVal T_ASSIGN Expr T_SEMICOLON  */
#line 631 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                         {
		// 赋值语句

		// 创建一个AST_OP_ASSIGN类型的中间节点，孩子为LVal($1)和Expr($3)
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_ASSIGN, (yyvsp[-3].node), (yyvsp[-1].node));
	}
#line 1966 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 46: /* Statement: Block  */
#line 637 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                {
		// 语句块

		// 内部已创建block节点，直接传递给Statement
		(yyval.node) = (yyvsp[0].node);
	}
#line 1977 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 47: /* Statement: Expr T_SEMICOLON  */
#line 643 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                           {
		// 表达式语句

		// 内部已创建表达式，直接传递给Statement
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1988 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 48: /* Statement: T_SEMICOLON  */
#line 649 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                      {
		// 空语句

		// 直接返回空指针，需要再把语句加入到语句块时要注意判断，空语句不要加入
		(yyval.node) = nullptr;
	}
#line 1999 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 49: /* Statement: T_IF T_L_PAREN Expr T_R_PAREN Statement  */
#line 655 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                                  {
		// if语句
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_IF, (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 2008 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 50: /* Statement: T_IF T_L_PAREN Expr T_R_PAREN Statement T_ELSE Statement  */
#line 659 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                                                   {
		// if-else语句
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_IF_ELSE, (yyvsp[-4].node), (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 2017 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 51: /* Statement: T_WHILE T_L_PAREN Expr T_R_PAREN Statement  */
#line 663 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                                     {
		// while语句
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_WHILE, (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 2026 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 52: /* Statement: T_BREAK T_SEMICOLON  */
#line 667 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                              {
		// break语句
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_BREAK);
	}
#line 2035 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 53: /* Statement: T_CONTINUE T_SEMICOLON  */
#line 671 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                 {
		// continue语句
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_CONTINUE);
	}
#line 2044 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 54: /* Expr: LogicalOrExp  */
#line 678 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                    {
        (yyval.node) = (yyvsp[0].node);
    }
#line 2052 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 55: /* LogicalOrExp: LogicalAndExp  */
#line 684 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                             {
        (yyval.node) = (yyvsp[0].node);
    }
#line 2060 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 56: /* LogicalOrExp: LogicalOrExp T_LOGICAL_OR LogicalAndExp  */
#line 687 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                              {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_LOGICAL_OR, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 2068 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 57: /* LogicalAndExp: RelExp  */
#line 693 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                       {
        (yyval.node) = (yyvsp[0].node);//$1;
    }
#line 2076 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 58: /* LogicalAndExp: LogicalAndExp T_LOGICAL_AND RelExp  */
#line 696 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                         {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_LOGICAL_AND, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 2084 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 59: /* RelExp: AddExp  */
#line 702 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                {
        (yyval.node) = (yyvsp[0].node);
    }
#line 2092 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 60: /* RelExp: RelExp T_LT AddExp  */
#line 705 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                         {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_LT, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 2100 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 61: /* RelExp: RelExp T_LE AddExp  */
#line 708 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                         {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_LE, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 2108 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 62: /* RelExp: RelExp T_GT AddExp  */
#line 711 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                         {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_GT, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 2116 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 63: /* RelExp: RelExp T_GE AddExp  */
#line 714 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                         {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_GE, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 2124 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 64: /* RelExp: RelExp T_EQ AddExp  */
#line 717 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                         {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_EQ, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 2132 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 65: /* RelExp: RelExp T_NE AddExp  */
#line 720 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                         {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_NE, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 2140 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 66: /* AddExp: MulExp  */
#line 726 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                {
        (yyval.node) = (yyvsp[0].node);
    }
#line 2148 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 67: /* AddExp: AddExp T_ADD MulExp  */
#line 729 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                              {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_ADD, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 2156 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 68: /* AddExp: AddExp T_SUB MulExp  */
#line 732 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                          {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_SUB, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 2164 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 69: /* MulExp: UnaryExp  */
#line 748 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                  {
        (yyval.node) = (yyvsp[0].node);
    }
#line 2172 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 70: /* MulExp: MulExp T_MUL UnaryExp  */
#line 751 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                            {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_MUL, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 2180 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 71: /* MulExp: MulExp T_DIV UnaryExp  */
#line 754 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                            {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_DIV, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 2188 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 72: /* MulExp: MulExp T_MOD UnaryExp  */
#line 757 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                            {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_MOD, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 2196 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 73: /* UnaryExp: PrimaryExp  */
#line 767 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                      {
		// 基本表达式

		// 传递到归约后的UnaryExp上
		(yyval.node) = (yyvsp[0].node);
	}
#line 2207 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 74: /* UnaryExp: T_ID T_L_PAREN T_R_PAREN  */
#line 773 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                   {
		// 没有实参的函数调用

		// 创建函数调用名终结符节点
		ast_node * name_node = ast_node::New(std::string((yyvsp[-2].var_id).id), (yyvsp[-2].var_id).lineno);

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[-2].var_id).id);

		// 实参列表
		ast_node * paramListNode = nullptr;

		// 创建函数调用节点，其孩子为被调用函数名和实参，实参为空，但函数内部会创建实参列表节点，无孩子
		(yyval.node) = create_func_call(name_node, paramListNode);

	}
#line 2228 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 75: /* UnaryExp: T_ID T_L_PAREN RealParamList T_R_PAREN  */
#line 789 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                                 {
		// 含有实参的函数调用

		// 创建函数调用名终结符节点
		ast_node * name_node = ast_node::New(std::string((yyvsp[-3].var_id).id), (yyvsp[-3].var_id).lineno);

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[-3].var_id).id);

		// 实参列表
		ast_node * paramListNode = (yyvsp[-1].node);

		// 创建函数调用节点，其孩子为被调用函数名和实参，实参不为空
		(yyval.node) = create_func_call(name_node, paramListNode);
	}
#line 2248 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 76: /* UnaryExp: T_SUB UnaryExp  */
#line 804 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                      {
        // 单目运算符 - 的表达式
        // 创建单目运算符节点
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_NEG, (yyvsp[0].node));
  	}
#line 2258 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 77: /* UnaryExp: T_ADD UnaryExp  */
#line 809 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                      {
        // 单目运算符 + 的表达式，直接返回操作数
        (yyval.node) = (yyvsp[0].node);
    }
#line 2267 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 78: /* UnaryExp: T_LOGICAL_NOT UnaryExp  */
#line 813 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                 {
		// 单目运算符 ! 的表达式
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_LOGICAL_NOT, (yyvsp[0].node));
    }
#line 2276 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 79: /* PrimaryExp: T_L_PAREN Expr T_R_PAREN  */
#line 822 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                       {
		// 带有括号的表达式
		(yyval.node) = (yyvsp[-1].node);
	}
#line 2285 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 80: /* PrimaryExp: T_DIGIT  */
#line 826 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                  {
        	// 无符号整型字面量

		// 创建一个无符号整型的终结符节点
		(yyval.node) = ast_node::New((yyvsp[0].integer_num));
	}
#line 2296 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 81: /* PrimaryExp: LVal  */
#line 832 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                {
		// 具有左值的表达式

		// 直接传递到归约后的非终结符号PrimaryExp
		(yyval.node) = (yyvsp[0].node);
	}
#line 2307 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 82: /* PrimaryExp: T_FLOAT_DIGIT  */
#line 838 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                        {
		// 浮点数
		(yyval.node) = ast_node::New((yyvsp[0].float_num));
	}
#line 2316 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 83: /* RealParamList: Expr  */
#line 848 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                     {
		// 创建实参列表节点，并把当前的Expr节点加入
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_REAL_PARAMS, (yyvsp[0].node));
	}
#line 2325 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 84: /* RealParamList: RealParamList T_COMMA Expr  */
#line 852 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                                     {
		// 左递归增加实参表达式
		(yyval.node) = (yyvsp[-2].node)->insert_son_node((yyvsp[0].node));
	}
#line 2334 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 85: /* LVal: T_ID  */
#line 859 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
            {
		// 变量名终结符

		// 创建变量名终结符节点
		(yyval.node) = ast_node::New((yyvsp[0].var_id));

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[0].var_id).id);
	}
#line 2348 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 86: /* LVal: T_ID ArrayIndices  */
#line 868 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"
                            {
		// 数组变量访问

		// 创建变量名终结符节点
		ast_node * id_node = ast_node::New((yyvsp[-1].var_id));

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[-1].var_id).id);

		// 创建数组访问节点
		(yyval.node) = createArrayAccessNode(id_node, (yyvsp[0].node));
	}
#line 2365 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;


#line 2369 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/autogenerated/MiniCBison.cpp"

      default: break;
    }
  /* User semantic actions sometimes alter yychar, and that requires
     that yytoken be updated with the new translation.  We take the
     approach of translating immediately before every use of yytoken.
     One alternative is translating here after every semantic action,
     but that translation would be missed if the semantic action invokes
     YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
     if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
     incorrect destructor might then be invoked immediately.  In the
     case of YYERROR or YYBACKUP, subsequent parser actions might lead
     to an incorrect destructor call or verbose syntax error message
     before the lookahead is translated.  */
  YY_SYMBOL_PRINT ("-> $$ =", YY_CAST (yysymbol_kind_t, yyr1[yyn]), &yyval, &yyloc);

  YYPOPSTACK (yylen);
  yylen = 0;

  *++yyvsp = yyval;

  /* Now 'shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */
  {
    const int yylhs = yyr1[yyn] - YYNTOKENS;
    const int yyi = yypgoto[yylhs] + *yyssp;
    yystate = (0 <= yyi && yyi <= YYLAST && yycheck[yyi] == *yyssp
               ? yytable[yyi]
               : yydefgoto[yylhs]);
  }

  goto yynewstate;


/*--------------------------------------.
| yyerrlab -- here on detecting error.  |
`--------------------------------------*/
yyerrlab:
  /* Make sure we have latest lookahead translation.  See comments at
     user semantic actions for why this is necessary.  */
  yytoken = yychar == YYEMPTY ? YYSYMBOL_YYEMPTY : YYTRANSLATE (yychar);
  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;
      yyerror (YY_("syntax error"));
    }

  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
         error, discard it.  */

      if (yychar <= YYEOF)
        {
          /* Return failure if at end of input.  */
          if (yychar == YYEOF)
            YYABORT;
        }
      else
        {
          yydestruct ("Error: discarding",
                      yytoken, &yylval);
          yychar = YYEMPTY;
        }
    }

  /* Else will try to reuse lookahead token after shifting the error
     token.  */
  goto yyerrlab1;


/*---------------------------------------------------.
| yyerrorlab -- error raised explicitly by YYERROR.  |
`---------------------------------------------------*/
yyerrorlab:
  /* Pacify compilers when the user code never invokes YYERROR and the
     label yyerrorlab therefore never appears in user code.  */
  if (0)
    YYERROR;
  ++yynerrs;

  /* Do not reclaim the symbols of the rule whose action triggered
     this YYERROR.  */
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  yystate = *yyssp;
  goto yyerrlab1;


/*-------------------------------------------------------------.
| yyerrlab1 -- common code for both syntax error and YYERROR.  |
`-------------------------------------------------------------*/
yyerrlab1:
  yyerrstatus = 3;      /* Each real token shifted decrements this.  */

  /* Pop stack until we find a state that shifts the error token.  */
  for (;;)
    {
      yyn = yypact[yystate];
      if (!yypact_value_is_default (yyn))
        {
          yyn += YYSYMBOL_YYerror;
          if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYSYMBOL_YYerror)
            {
              yyn = yytable[yyn];
              if (0 < yyn)
                break;
            }
        }

      /* Pop the current state because it cannot handle the error token.  */
      if (yyssp == yyss)
        YYABORT;


      yydestruct ("Error: popping",
                  YY_ACCESSING_SYMBOL (yystate), yyvsp);
      YYPOPSTACK (1);
      yystate = *yyssp;
      YY_STACK_PRINT (yyss, yyssp);
    }

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END


  /* Shift the error token.  */
  YY_SYMBOL_PRINT ("Shifting", YY_ACCESSING_SYMBOL (yyn), yyvsp, yylsp);

  yystate = yyn;
  goto yynewstate;


/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturnlab;


/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturnlab;


/*-----------------------------------------------------------.
| yyexhaustedlab -- YYNOMEM (memory exhaustion) comes here.  |
`-----------------------------------------------------------*/
yyexhaustedlab:
  yyerror (YY_("memory exhausted"));
  yyresult = 2;
  goto yyreturnlab;


/*----------------------------------------------------------.
| yyreturnlab -- parsing is finished, clean up and return.  |
`----------------------------------------------------------*/
yyreturnlab:
  if (yychar != YYEMPTY)
    {
      /* Make sure we have latest lookahead translation.  See comments at
         user semantic actions for why this is necessary.  */
      yytoken = YYTRANSLATE (yychar);
      yydestruct ("Cleanup: discarding lookahead",
                  yytoken, &yylval);
    }
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYABORT or YYACCEPT.  */
  YYPOPSTACK (yylen);
  YY_STACK_PRINT (yyss, yyssp);
  while (yyssp != yyss)
    {
      yydestruct ("Cleanup: popping",
                  YY_ACCESSING_SYMBOL (+*yyssp), yyvsp);
      YYPOPSTACK (1);
    }
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif

  return yyresult;
}

#line 882 "/home/code/exp04-minic-expr/npucompiler/frontend/flexbison/MiniC.y"



// 语法识别错误要调用函数的定义
void yyerror(char * msg)
{
    printf("Line %d: %s\n", yylineno, msg);
}

